# Generated by Django 5.1.2 on 2024-10-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_description_remove_track_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='last_played',
            new_name='last_play',
        ),
    ]
